### ISSUE TITLE
Warts are being specified 12 times each

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1314]
Running sbt under debug I find it passing 216 `-P:wartremover:` options to scalac - these 18 options, 12 times each. As a wild guess, every subproject adds them and wartremover uses them all everywhere.

```
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.While
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Var
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Throw
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Return
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Null
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments
  12 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd
```

**Comment by paulp** [comment]
I can confirm it's once per subproject. No idea why though.

**Comment by paulp** [comment]
On a compiler crash.

[error]   Something is wrong: cannot find A in applied type quasar.qscript.NormalizableT[T]
[error]    sought  A in NormalizableT
[error]  classSym  NormalizableT in qscript
[error]   tparams  T in NormalizableT
[error]
[error]      while compiling: /s/slamdata/quasar/connector/src/main/scala/quasar/qscript/QScriptCore.scala
[error]         during phase: typer
[error]      library version: version 2.11.8
[error]     compiler version: version 2.11.8
[error]   reconstructed args: -Ywarn-value-discard -target:jvm-1.8 -bootclasspath /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/classes:/Users/psp/.ivy2/local/org.typelevel/scala-library/2.11.8/jars/scala-library.jar -feature -language:implicitConversions -language:higherKinds -language:existentials -Ypartial-unification 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Any2StringAdd 
-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments 
-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass 
-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal 
-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf 
-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions 
-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ListOps 
-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures 
-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Null 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Product 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Return 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw 
-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString 
-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial 
-P:wartremover:only-warn-traverser:org.wartremover.warts.Var 
-P:wartremover:only-warn-traverser:org.wartremover.warts.While 
-Xplugin:/Users/psp/.ivy2/cache/org.wartremover/wartremover_2.11/jars/wartremover_2.11-1.1.1.jar -Xplugin:/Users/psp/.ivy2/cache/org.spire-math/kind-projector_2.11/jars/kind-projector_2.11-0.9.0.jar -Xplugin:/Users/psp/.ivy2/cache/org.scalamacros/paradise_2.11.8/jars/paradise_2.11.8-2.1.0.jar -Ywarn-numeric-widen -unchecked -Xfuture -Yno-adapted-args -Ydelambdafy:method -Ywarn-unused-import -Yliteral-types -deprecation -Yno-imports -Xfatal-warnings -Ybackend:GenBCode -classpath /s/slamdata/quasar/connector/target/scala-2.11/classes:/s/slamdata/quasar/ejson/target/scala-2.11/classes:/s/slamdata/quasar/foundation/target/scala-2.11/classes:/s/slamdata/quasar/effect/target/scala-2.11/classes:/s/slamdata/quasar/js/target/scala-2.11/classes:/s/slamdata/quasar/frontend/target/scala-2.11/classes:/s/slamdata/quasar/sql/target/scala-2.11/classes:/Users/psp/.ivy2/cache/org.threeten/threetenbp/jars/threetenbp-1.3.2.jar:/Users/psp/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.2.4.jar:/Users/psp/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.2.4.jar:/Users/psp/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.2.4.jar:/Users/psp/.ivy2/cache/org.scalaz/scalaz-iteratee_2.11/bundles/scalaz-iteratee_2.11-7.2.4.jar:/Users/psp/.ivy2/cache/org.scalaz.stream/scalaz-stream_2.11/bundles/scalaz-stream_2.11-0.8.3a.jar:/Users/psp/.ivy2/cache/org.scodec/scodec-bits_2.11/bundles/scodec-bits_2.11-1.1.0.jar:/Users/psp/.ivy2/cache/com.github.julien-truffaut/monocle-core_2.11/jars/monocle-core_2.11-1.2.2.jar:/Users/psp/.ivy2/cache/io.argonaut/argonaut_2.11/jars/argonaut_2.11-6.2-M3.jar:/Users/psp/.ivy2/local/org.typelevel/scala-reflect/2.11.8/jars/scala-reflect.jar:/Users/psp/.ivy2/cache/io.argonaut/argonaut-scalaz_2.11/jars/argonaut-scalaz_2.11-6.2-M3.jar:/Users/psp/.ivy2/cache/org.typelevel/shapeless-scalaz_2.11/jars/shapeless-scalaz_2.11-0.4.jar:/Users/psp/.ivy2/cache/org.typelevel/shapeless-contrib-common_2.11/jars/shapeless-contrib-common_2.11-0.4.jar:/Users/psp/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.3.1.jar:/Users/psp/.ivy2/cache/org.typelevel/macro-compat_2.11/jars/macro-compat_2.11-1.1.1.jar:/Users/psp/.ivy2/cache/com.slamdata/matryoshka-core_2.11/jars/matryoshka-core_2.11-0.11.1.jar:/Users/psp/.ivy2/cache/com.github.mpilquist/simulacrum_2.11/jars/simulacrum_2.11-0.7.0.jar:/Users/psp/.ivy2/cache/com.slamdata/pathy-core_2.11/jars/pathy-core_2.11-0.2.2.jar:/Users/psp/.ivy2/cache/eu.timepit/refined_2.11/jars/refined_2.11-0.5.0.jar:/Users/psp/.ivy2/local/org.typelevel/scala-compiler/2.11.8/jars/scala-compiler.jar:/Users/psp/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar:/Users/psp/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/Users/psp/.ivy2/cache/com.github.tototoshi/scala-csv_2.11/jars/scala-csv_2.11-1.3.1.jar:/Users/psp/.ivy2/cache/com.github.julien-truffaut/monocle-macro_2.11/jars/monocle-macro_2.11-1.2.2.jar:/Users/psp/.ivy2/cache/org.http4s/http4s-core_2.11/jars/http4s-core_2.11-0.14.1a.jar:/Users/psp/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.5.0.jar:/Users/psp/.ivy2/cache/org.http4s/http4s-websocket_2.11/jars/http4s-websocket_2.11-0.1.3.jar:/Users/psp/.ivy2/cache/org.log4s/log4s_2.11/jars/log4s_2.11-1.3.0.jar:/Users/psp/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar:/Users/psp/.ivy2/cache/org.parboiled/parboiled_2.11/bundles/parboiled_2.11-2.1.2.jar:/Users/psp/.ivy2/cache/com.slamdata/pathy-argonaut_2.11/jars/pathy-argonaut_2.11-0.2.2.jar:/Users/psp/.ivy2/cache/com.slamdata/pathy-scalacheck_2.11/jars/pathy-scalacheck_2.11-0.2.2.jar:/Users/psp/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.5.jar:/Users/psp/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/psp/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.1.1.jar:/Users/psp/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.1.1.jar -Ywarn-dead-code

**Comment by sellout** [comment]
Is this a result of the `.aggregate` on the root project somehow? At this point, we definitely disable specific warts in individual subprojects, so I don’t understand how it could be applying the global setting across _all_ projects, without affecting that.

Notably, in this case, `AsInstanceOf` is missing, as it should be for the connector project. So it seems like it can’t just be adding all of the ones from each subproject.

**Comment by paulp** [comment]
@sellout I don't understand the behavior, but my earlier observation about it being connected to the number of subprojects was based on adding a subproject and seeing the count increase by the number of warts.

**Comment by nicflores** [comment]
Running sbt in debug mode and printing out the scalac options I don't see wartremover options mentioned above.

```
> show web/compile:scalacOptions
[debug] > show web/compile:scalacOptions
[debug] Evaluating tasks: web/compile:scalacOptions
[debug] Running task... Cancel: Null, check cycles: false, forcegc: true
.
...snip...
.
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Forcing garbage collection...
[info] * -deprecation
[info] * -encoding
[info] * UTF-8
[info] * -feature
[info] * -language:existentials
[info] * -language:higherKinds
[info] * -language:implicitConversions
[info] * -unchecked
[info] * -Xfatal-warnings
[info] * -Xfuture
[info] * -Yno-adapted-args
[info] * -Yno-imports
[info] * -Ywarn-dead-code
[info] * -Ywarn-numeric-widen
[info] * -Ywarn-value-discard
[info] * -Ydelambdafy:method
[info] * -Yliteral-types
[info] * -Ypartial-unification
[info] * -Ywarn-unused-import
[info] * -target:jvm-1.8
[info] * -Ybackend:GenBCode
[info] * -Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalamacros/paradise_2.11.8/2.1.0/paradise_2.11.8-2.1.0.jar
[info] * -Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/spire-math/kind-projector_2.11/0.9.3/kind-projector_2.11-0.9.3.jar
[info] * -Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/wartremover/wartremover_2.11/2.0.3/wartremover_2.11-2.0.3.jar
```

Running `show scalacOptions` also bring up anything.
It is possible this has been fixed.

**Comment by paulp** [comment]
It's not fixed. Just do `./sbt -d ejson/compile` or similar from a clean checkout. Now 42 times apiece.
```
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.AsInstanceOf
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Equals
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Null
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Product
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Return
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.StringPlusAny
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Throw
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.ToString
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.TraversableOps
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.Var
  42 [debug]   -P:wartremover:only-warn-traverser:org.wartremover.warts.While
```

**Comment by sellout** [comment]
42? Sounds like progress! 😆

**Comment by nicflores** [comment]
Thanks for the feedback @paulp.

**Comment by nicflores** [comment]
This issue has been pointed out by @RandGalt on the Wartremover Gitter channel. This PR should fix the issue: https://github.com/wartremover/wartremover/pull/352
Once the PR is merged a version bump to wartremover should fix this issue.

**Comment by nicflores** [comment]
`sbt-slamdata` has been upgraded to use Wartremover v2.1.0. This version of Wartremover includes PR wartremover/wartremover#352 which will fix the issue reported above once Quasar is upgraded to use version `0.3.1` of `sbt-slamdata`.

**Comment by nicflores** [comment]
After annotating many Recursive warts, I just verified that version v2.1.1 of wartremover fixes this issue:

```
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-deprecation
[debug] 	-encoding
[debug] 	UTF-8
[debug] 	-feature
[debug] 	-language:existentials
[debug] 	-language:higherKinds
[debug] 	-language:implicitConversions
[debug] 	-unchecked
[debug] 	-Xfatal-warnings
[debug] 	-Xfuture
[debug] 	-Yno-adapted-args
[debug] 	-Yno-imports
[debug] 	-Ywarn-dead-code
[debug] 	-Ywarn-numeric-widen
[debug] 	-Ywarn-value-discard
[debug] 	-Ydelambdafy:method
[debug] 	-Yliteral-types
[debug] 	-Ypartial-unification
[debug] 	-Ywarn-unused-import
[debug] 	-target:jvm-1.8
[debug] 	-Ybackend:GenBCode
[debug] 	-Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalamacros/paradise_2.11.8/2.1.0/paradise_2.11.8-2.1.0.jar
[debug] 	-Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/spire-math/kind-projector_2.11/0.9.3/kind-projector_2.11-0.9.3.jar
[debug] 	-Xplugin:/Users/nicandroflores/.coursier/cache/v1/https/repo1.maven.org/maven2/org/wartremover/wartremover_2.11/2.1.1/wartremover_2.11-2.1.1.jar
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.ArrayEquals
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.AsInstanceOf
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.DefaultArguments
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.EitherProjectionPartial
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Enumeration
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Equals
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalCaseClass
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.FinalVal
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.IsInstanceOf
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.JavaConversions
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.LeakingSealed
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.MutableDataStructures
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.NonUnitStatements
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Null
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Option2Iterable
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.OptionPartial
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Overloading
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Product
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Recursion
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Return
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Serializable
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.StringPlusAny
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Throw
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.ToString
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.TraversableOps
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.TryPartial
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.Var
[debug] 	-P:wartremover:only-warn-traverser:org.wartremover.warts.While
[debug] 	-bootclasspath
```

next steps are to either override wartremover in Quasar since the latest version of sbt-slamdata brings in wartremover v2.1.0 which doesn't work due to a ScalaReflection bug or fix the compile time issue we are seeing in https://github.com/jedesah/Quasar/tree/topic/remove_common_dependencies
