### ISSUE TITLE
convertToQScript against a valid LP produces "unsupported ordering function" error

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1411]
An `unsupported ordering function` error occurs when calling `convertToQScript` on the LP for `select * from zips order by city`.

```
lp: Let('__tmp0)
├─ Invoke(SQUASH)
│  ╰─ Read(./zips)
╰─ Invoke(ORDER BY)
   ├─ Free('__tmp0)
   ├─ Invoke(MAKE_ARRAY)
   │  ╰─ ObjectProject('__tmp0["city"])
   ╰─ Invoke(MAKE_ARRAY)
      ╰─ Str("ASC")
```

**Comment by sellout** [comment]
This is fixed in #1567, right @alissapajer?

**Comment by alissapajer** [comment]
@sellout so the error is not produced anymore as of PR #1567. But the query is still not optimal. That PR added a pending test for this query, so I'll close this ticket, and then open a new one for the pending test, like we've done for the other pending tests.

**Comment by alissapajer** [comment]
#1578 is the pending test issue.
