### ISSUE TITLE
QScript transformation for connectors that don’t have order-preserving Reduce.

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1755]
rabbit [5:12 PM]  
I want to discuss potential bug (check if it is a bug or feature :slightly_smiling_face: )

[5:13]  
query: `select distinct city from zips order by pop desc limit 5`

[5:13]  
the plan that I get first sorts, then runs aggregation

[5:14]  
this is an issue for Spark because when running any `Reduce` aggregation I’m loosing order

sellout [5:15 PM]  
Yeah, that's part of the semantics of SQL distinct – it has to grab the first value from the sorted results.

[5:16]  
What's the ReduceFunc in the Reduce?

rabbit [5:17 PM]  
then it means that all `"(….) group by (…) order by (…)"` will be broken in Spark

[5:18]  
@sellout let me check the plan, one moment

[5:19]  
@sellout qscript output is long, should I paste it here ?

sellout [5:38 PM]  
So, yeah, it’s using Arbitrary … probably because First isn’t yet in master :wink:

[5:38]  
So, Mongo has to work around this issue, too …

[5:39]  
Does Spark at least go through the results in order? I.e., how can you make `First` work at all? (edited)

[5:40]  
Mongo’s solution is, if it finds a Reduce, it looks to see if there’s a Sort before it, and if so, it duplicates again after the Reduce.

sellout [5:46 PM]  
And … I wouldn’t be surprised if this affected other backends. Can probably replace the Mongo-specific transformation with an optional QScript one. Like `ensureReduceOrder` or something.

sellout [6:27 PM]  
@rabbit ↑ just calling attention to my comments, since I didn’t mention you.

rabbit [6:45 PM]  
reading

[6:46]  
what do u mean by `First` ?

sellout [6:46 PM]  
@rabbit `First` is another aggregator, like `Sum` or `Count`. It grabs the first element from the set to be reduced.

rabbit [6:46 PM]  
`Reduce` will unfortunately loose order

[6:47]  
i mean it will shuffle data and it will not be in previous order

[6:47]  
`First` is easy to be implemented

[6:47]  
as there is `RDD.first` function in Spark API

[6:47]  
the problem is that we first sort then reduce

[6:48]  
we would have to sort the result after reduce

sellout [6:48 PM]  
Yeah – as I said, that’s what we do in Mongo.

[6:48]  
Sort before the reduce, and again after.

rabbit [6:49 PM]  
but … how is that possible, how do u know by which elements u neeed to sort?

[6:49]  
or u do something to the QScript

[6:49]  
some `QScript => QScript` optimilization

[6:50]  
is that what u meant by `ensureReduceOrder` :slightly_smiling_face:

[6:50]  
if so I will be happy to have one :wink:

sellout [6:50 PM]  
I forget at what point it’s done at the moment, but it does require some rewriting to make sure the right values are preserved. I would have to do some work to make it a QScript optimization, but it sounds like the right place to do it – both Mongo and Spark (and probably other?) connectors would use it.

**Comment by sellout** [comment]
This is fixed on the new Mongo branch.

The SQL compiler now inserts sort/groupBy/sort when necessary. Potentially in the future we could have a rewrite that eliminates the second sort for connectors that _do_ have an order-preserving `Reduce`, but the current approach should work for all connectors.

**Comment by alissapajer** [comment]
There are some remaining tests that hit this case that are still not passing in new mongo (caseVariations.test, caseWithGroup.test, citiesByLargestZip.test, shortCities.test). We need to confirm this fix is indeed present on new mongo and then determine what else is going wrong in these queries.

**Comment by alissapajer** [comment]
This is confirmed as fixed on next-major. The tests that are failing are failing on mongo for separate reasons.
